[theme]
primaryColor = "#B9822F"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6efe9"
textColor = "#1a1413"
font = "sans serif"
baseRadius = "full"

[server]
maxUploadSize = 50
enableXsrfProtection = true
headless = true

[browser]
gatherUsageStats = false
