[theme]
primaryColor = "#15A35A"
backgroundColor = "#F2FAF5"
secondaryBackgroundColor = "#E8F7EF"
textColor = "#173029"
font = "sans serif"
baseRadius = "full"

[server]
maxUploadSize = 50
enableXsrfProtection = true
headless = true

[browser]
gatherUsageStats = false
